version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: tech11-be
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      # Override or set defaults for specific variables if needed
      - DATABASE_URL=sqlite:///./app.db
      - ENVIRONMENT=production
    volumes:
      # Persist database
      - ./app.db:/app/app.db
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

