"""add_research_caching_and_tracking_fields

Revision ID: 39c4b9d02dd1
Revises: 61e75648bc1a
Create Date: 2025-10-11 23:11:58.105001

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "39c4b9d02dd1"
down_revision: Union[str, Sequence[str], None] = "61e75648bc1a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Drop old table
    op.drop_index(op.f("ix_research_id"), table_name="research")
    op.drop_index(op.f("ix_research_title"), table_name="research")
    op.drop_table("research")

    # Create new table with all fields
    op.create_table(
        "research",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(length=500), nullable=False),
        sa.Column("abstract", sa.Text(), nullable=False),
        sa.Column("domain", sa.String(length=50), nullable=False),
        sa.Column("authors", sa.JSON(), nullable=True),
        sa.Column("published_date", sa.String(length=50), nullable=True),
        sa.Column("updated_date", sa.String(length=50), nullable=True),
        sa.Column("categories", sa.JSON(), nullable=True),
        sa.Column("pdf_url", sa.String(length=500), nullable=True),
        sa.Column("arxiv_url", sa.String(length=500), nullable=True),
        sa.Column("citation_count", sa.Integer(), nullable=False, server_default="0"),
        sa.Column("relevance_score", sa.Float(), nullable=False, server_default="0.0"),
        sa.Column("object_key", sa.String(length=500), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=True,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=True,
        ),
        sa.PrimaryKeyConstraint("id"),
    )

    # Create indexes
    op.create_index(op.f("ix_research_id"), "research", ["id"], unique=False)
    op.create_index(op.f("ix_research_title"), "research", ["title"], unique=False)
    op.create_index(op.f("ix_research_domain"), "research", ["domain"], unique=False)
    op.create_index(
        op.f("ix_research_arxiv_url"), "research", ["arxiv_url"], unique=False
    )
    op.create_index(
        op.f("ix_research_created_at"), "research", ["created_at"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Drop new table and indexes
    op.drop_index(op.f("ix_research_created_at"), table_name="research")
    op.drop_index(op.f("ix_research_arxiv_url"), table_name="research")
    op.drop_index(op.f("ix_research_domain"), table_name="research")
    op.drop_index(op.f("ix_research_title"), table_name="research")
    op.drop_index(op.f("ix_research_id"), table_name="research")
    op.drop_table("research")

    # Recreate old table
    op.create_table(
        "research",
        sa.Column("id", sa.INTEGER(), nullable=False),
        sa.Column("title", sa.VARCHAR(length=500), nullable=False),
        sa.Column("abstract", sa.TEXT(), nullable=False),
        sa.Column(
            "created_at",
            sa.DATETIME(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=True,
        ),
        sa.Column(
            "updated_at",
            sa.DATETIME(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=True,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_research_title"), "research", ["title"], unique=False)
    op.create_index(op.f("ix_research_id"), "research", ["id"], unique=False)
    # ### end Alembic commands ###
