"""create video table

Revision ID: 6278a00cd576
Revises: 4ddb57a0ca5c
Create Date: 2025-10-15 13:46:25.862180

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "6278a00cd576"
down_revision: Union[str, Sequence[str], None] = "4ddb57a0ca5c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "video",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("research_id", sa.Integer(), nullable=False),
        sa.Column("object_key", sa.String(length=500), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=True,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=True,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_video_id"), "video", ["id"], unique=False)
    op.create_index(
        op.f("ix_video_research_id"), "video", ["research_id"], unique=False
    )
    op.create_index(op.f("ix_video_created_at"), "video", ["created_at"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_video_created_at"), table_name="video")
    op.drop_index(op.f("ix_video_research_id"), table_name="video")
    op.drop_index(op.f("ix_video_id"), table_name="video")
    op.drop_table("video")
    # ### end Alembic commands ###
