"""create_summary_table

Revision ID: da486a358923
Revises: e30d316da0b6
Create Date: 2025-10-14 17:17:29.784204

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "da486a358923"
down_revision: Union[str, Sequence[str], None] = "e30d316da0b6"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "summary",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("research_id", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(length=500), nullable=False),
        sa.Column("summary", sa.Text(), nullable=False),
        sa.Column("pdf_link", sa.String(length=500), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=True,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=True,
        ),
        sa.ForeignKeyConstraint(
            ["research_id"],
            ["research.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_summary_created_at"), "summary", ["created_at"], unique=False
    )
    op.create_index(op.f("ix_summary_id"), "summary", ["id"], unique=False)
    op.create_index(
        op.f("ix_summary_research_id"), "summary", ["research_id"], unique=False
    )
    op.create_index(op.f("ix_summary_title"), "summary", ["title"], unique=False)
    op.drop_index(op.f("ix_tts_research_id"), table_name="tts")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f("ix_tts_research_id"), "tts", ["research_id"], unique=False)
    op.drop_index(op.f("ix_summary_title"), table_name="summary")
    op.drop_index(op.f("ix_summary_research_id"), table_name="summary")
    op.drop_index(op.f("ix_summary_id"), table_name="summary")
    op.drop_index(op.f("ix_summary_created_at"), table_name="summary")
    op.drop_table("summary")
    # ### end Alembic commands ###
