"""create_tts_table

Revision ID: e30d316da0b6
Revises: 39c4b9d02dd1
Create Date: 2025-10-13 14:23:27.754320

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "e30d316da0b6"
down_revision: Union[str, Sequence[str], None] = "39c4b9d02dd1"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "tts",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("research_id", sa.Integer(), nullable=False),
        sa.Column("summary", sa.Text(), nullable=False),
        sa.Column("explainer", sa.Text(), nullable=False),
        sa.Column("object_key", sa.String(length=500), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=True,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=True,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_tts_id"), "tts", ["id"], unique=False)
    op.create_index(op.f("ix_tts_created_at"), "tts", ["created_at"], unique=False)
    op.create_index(op.f("ix_tts_research_id"), "tts", ["research_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_tts_research_id"), table_name="tts")
    op.drop_index(op.f("ix_tts_created_at"), table_name="tts")
    op.drop_index(op.f("ix_tts_id"), table_name="tts")
    op.drop_table("tts")
    # ### end Alembic commands ###
