name: CI

on:
  pull_request:
    branches: [ main ]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'

    - name: Install uv
      uses: astral-sh/setup-uv@v3
      with:
        version: "latest"

    - name: Install dependencies
      run: |
        uv sync --dev

    - name: Run Black (formatting check)
      run: |
        uv run black --check --diff . --extend-exclude="legacy/"

    - name: Run isort (import sorting check)
      run: |
        uv run isort --check-only --diff . --extend-skip-glob="legacy/*"

    - name: Run Ruff (linting)
      run: |
        uv run ruff check . --extend-exclude="legacy"
